### PR TITLE
Add safe directory

### PR DESCRIPTION
**Pull request by sanders41**
@prrao87 maybe it has something to do with the theme and sub modules? I'm not sure if this will make a difference but maybe worth a try.

### CODE REVIEW

**Comment by prrao87** [comment]
Hmm. I feel like I've tried this in one of my iterations, but I suppose it couldn't hurt to give it another try. Thanks a lot for the PR!

**Comment by sanders41** [comment]
:frowning_face: looks like it didn't make a difference. What I would suggest trying next is going back to the baseline 0.17.2 action, let it fail and then re-run with debug logging turned on. Maybe there will be some more detail to pin down the issue.

**Comment by prrao87** [comment]
Yup, I figured the same. But the debug logs don't tell me anything at all. Does [this](https://github.com/thedataquarry/thedataquarry.github.io/actions/runs/7038334534/job/19155060468) make any sense to you?

**Comment by sanders41** [comment]
Unfortunately the logs only show what we already know and nothing that we actually want to see gets added.

**Pull request merged**
